package adapter

import (
	"maps"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/FacileStudio/Mycelium/internal/cell"
)

// TestAgentsWritesTheStandardPaths pins the two paths that are the entire
// point of this adapter. They are asserted as exact absolute paths rather
// than as suffixes because a near-miss — .agent/, agents/skills/vhs.md — is
// silently useless: the consumer reads its own path, finds nothing, and
// reports no error anywhere.
func TestAgentsWritesTheStandardPaths(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	out, err := (&Agents{}).Generate(Input{
		Rules:  []cell.NamedFile{{Name: "r", Content: "RULE BODY"}},
		Skills: []cell.NamedFile{{Name: "vhs", Content: "VHS SKILL BODY"}},
	})
	if err != nil {
		t.Fatal(err)
	}

	agentsMd := filepath.Join(home, ".agents", "AGENTS.md")
	skillMd := filepath.Join(home, ".agents", "skills", "vhs", "SKILL.md")
	written := slices.Sorted(maps.Keys(out.Files))

	if _, ok := out.Files[agentsMd]; !ok {
		t.Fatalf("no AGENTS.md at %s, got %v", agentsMd, written)
	}
	if out.Files[skillMd] != "VHS SKILL BODY" {
		t.Errorf("no skill at %s, got %v", skillMd, written)
	}
	if !strings.Contains(out.Files[agentsMd], "RULE BODY") {
		t.Error("AGENTS.md missing rules")
	}
	if !strings.Contains(out.Files[agentsMd], "mycelium recap") {
		t.Error("AGENTS.md missing recap reminder")
	}
	if strings.Contains(out.Files[agentsMd], "VHS SKILL BODY") {
		t.Error("skill must NOT be inlined into AGENTS.md")
	}
}

// TestAgentsAnnouncesItselfAsGenerated covers the one thing that separates
// this adapter's output from its siblings'. ~/.agents/AGENTS.md is a path the
// specification tells users to write by hand, so a mycelium-written file there
// has to say it is mycelium's and that an edit will not survive. The notice has
// to lead the file: a provenance line halfway down is one nobody reads before
// editing.
func TestAgentsAnnouncesItselfAsGenerated(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	out, err := (&Agents{}).Generate(Input{Rules: []cell.NamedFile{{Name: "r", Content: "RULE"}}})
	if err != nil {
		t.Fatal(err)
	}

	body := out.Files[filepath.Join(home, ".agents", "AGENTS.md")]
	if !strings.HasPrefix(body, "<!-- Generated by") {
		t.Fatalf("AGENTS.md must open with the generated notice, got %.60q", body)
	}
	if !strings.Contains(body, "overwritten") {
		t.Error("notice must say an edit does not survive the next run")
	}
}

func TestAgentsTargetPathIsTheStandardBase(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	paths := (&Agents{}).TargetPaths()
	want := filepath.Join(home, ".agents", "AGENTS.md")
	if len(paths) != 1 || paths[0] != want {
		t.Fatalf("TargetPaths() = %v, want [%s]", paths, want)
	}
}

// TestAgentsIsRegistered covers the init() wiring rather than the adapter:
// without it `mycelium install agents` fails at lookup and `--all` skips the
// tree entirely, both without touching any code this file's other tests run.
func TestAgentsIsRegistered(t *testing.T) {
	a, err := Get("agents")
	if err != nil {
		t.Fatalf("Get(\"agents\"): %v", err)
	}
	if a.Name() != "agents" {
		t.Errorf("Name() = %q, want \"agents\"", a.Name())
	}
}
