package adapter

import (
	"os"
	"path/filepath"
	"strings"
)

// Agents is the adapter for the AGENTS.md specification's own global-base
// path, ~/.agents.
//
// It is named for the specification rather than for any one tool, and that is
// the whole reason it exists. Every other adapter here writes a vendor
// directory that exactly one program reads; ~/.agents/AGENTS.md and
// ~/.agents/skills/ are stewarded cross-vendor, so one generated tree serves
// every agent that follows the convention. nacelle reads both paths today
// (tui/context.go and tui/skills.go), pi reads its own equivalent, and a tool
// that adopts the standard tomorrow is served without a new adapter.
type Agents struct{}

// generatedNotice is the provenance line ~/.agents/AGENTS.md carries.
//
// Only this adapter emits one, and the asymmetry is the point. Every other
// adapter writes inside a directory its own vendor owns, where mycelium being
// the author is unambiguous. ~/.agents is a cross-vendor standard path, and
// the specification points the person running mycelium at that exact file for
// their own global instructions — so something appearing there has to say
// where it came from and what happens to an edit.
//
// Phrased as provenance rather than "DO NOT EDIT" on purpose: this file is
// read by models as instructions, and a prohibition meant for the human reads
// to them as one aimed at themselves.
//
// The SKILL.md files this adapter also writes deliberately get no notice, and
// must not. A SKILL.md opens with YAML frontmatter, which has to be the first
// line of the file: anything prepended to it — this comment included — breaks
// the parse for every consumer that reads the name and description out of it.
// The inconsistency is the correct behaviour, not an oversight to tidy up.
const generatedNotice = "<!-- Generated by `mycelium install agents` from ~/.mycelium/rules and " +
	"~/.mycelium/skills. Edits here are overwritten on the next run; change the source instead. -->"

func init() {
	Register(&Agents{})
}

func (a *Agents) Name() string { return "agents" }

func (a *Agents) TargetPaths() []string {
	home, _ := os.UserHomeDir()
	return []string{
		filepath.Join(home, ".agents", "AGENTS.md"),
	}
}

func (a *Agents) Generate(input Input) (*Output, error) {
	var sections []string

	sections = append(sections, recapReminder)

	for _, rule := range input.Rules {
		sections = append(sections, strings.TrimSpace(rule.Content))
	}

	if input.Machine != "" {
		sections = append(sections, strings.TrimSpace(input.Machine))
	}

	out := &Output{Files: make(map[string]string)}

	home, _ := os.UserHomeDir()
	agentsMd := filepath.Join(home, ".agents", "AGENTS.md")
	out.Files[agentsMd] = generatedNotice + "\n\n" + strings.Join(sections, "\n\n---\n\n") + "\n"

	for _, skill := range input.Skills {
		skillPath := filepath.Join(home, ".agents", "skills", skill.Name, "SKILL.md")
		out.Files[skillPath] = skill.Content
	}

	return out, nil
}
